### ISSUE TITLE
Update for svg-react-loader@v0.4.0

### ISSUE THREAD

**Issue by jhamlet** [RyanCCollins/scalable-react-boilerplate#1]
Hi there,

Just dropping a friendly note that I am updating `svg-react-loader` to version 0.4.0 very soon and it has changed a bit.

The biggest change that may affect you is that it no longer will require `babel` as it outputs completely valid es2015 syntax, but is compatible with ES6-7 module loading.

It has a [few other features](https://github.com/jhamlet/svg-react-loader/blob/version-0.4.0/README-v0.4.0.md) if it intrigues you.

Thanks,

;-j

**Comment by RyanCCollins** [comment]
Hi!! Really appreciate that!  I just released this project today as one of my first open-source projects and my heart sank seeing an issue already.  So glad that it was just a friendly note!

Regards,

Ryan Collins
