### ISSUE TITLE
Got code ELIFECYCLE after running 'npm run dev'

### ISSUE THREAD

**Issue by zhangtreefish** [RyanCCollins/scalable-react-boilerplate#22]
Upon  'npm run start' I got:  
`npm ERR! '  code ELIFECYCLE: alumni-client@1.0.0 dev: ``npm bin`/webpack-dev-server``
, and   
``npm' is not recognized as an internal or external command, operable program or batch file. `

I am using Windows 10. I changed node and npm versions to match those defined in package.json, and still got the same error. Below is the log for the boilerplate app:
[npm-debug.txt](https://github.com/RyanCCollins/scalable-react-boilerplate/files/435650/npm-debug.txt)

And here is a screenshot of the error message for the alumni app:
![npmnotrecognized](https://cloud.githubusercontent.com/assets/10746052/17955097/53675f76-6a45-11e6-8173-24f95cd8bcdd.jpg)

**Comment by RyanCCollins** [comment]
Thanks, I believe I know what is happening.  Your commandline is unable to recognize that command.  It's a windows thing.  I will see if I can get it working and report to you how I did it.  Thanks!

**Comment by RyanCCollins** [comment]
@zhangtreefish I am going to close this, pending updates and tests!  I will get it working on Windows.  Thanks again for reporting it!
