### ISSUE TITLE
Test suite was empty, cannot resolve module 'isparta'

### ISSUE THREAD

**Issue by farmasek** [RyanCCollins/scalable-react-boilerplate#24]
Hi,
after clean clone it's runnable, without problem. But when i want to try tests by 'npm run test' i have these errors: 

```
ERROR in ./config/testing/test-bundler.js
Module not found: Error: Cannot resolve module 'chai-jsx' in E:\my-projects\scalable-react-boilerplate\config\testing
 @ ./config/testing/test-bundler.js 13:15-34
```
Which is fixable by npm install it. But with it, even after installing it there are 4 same warnings:

```
WARNING in ./app/src ([^\a]+).test\.js$
Module not found: Error: Cannot resolve module 'isparta' in E:\my-projects\scalable-react-boilerplate\app\src
 @ ./app/src ([^\a]+).test\.js$
```

It will start karma server, launch and start Chrome, connect it on socket but the test suite is empty:

`30 08 2016 21:30:58.254:WARN [karma]: Test suite was empty. `

Due to 0 tests are completed. I am running on Windows 10.

**Comment by RyanCCollins** [comment]
Thanks so much for sending this in. It's not the first issue I've had with the test suite and I believe we are going to transition towards using Jest instead.  We will have updates shortly!

**Comment by RyanCCollins** [comment]
New commit coming that fixes this nonsense!!! Sorry for the delay.
