### ISSUE TITLE
https://scalable-react-boilerplate.herokuapp.com/ is down

### ISSUE THREAD

**Issue by ro-savage** [RyanCCollins/scalable-react-boilerplate#52]
Just FYI https://scalable-react-boilerplate.herokuapp.com/ is currently (29 Nov 16) showing an error.

![image](https://cloud.githubusercontent.com/assets/9244507/20666909/75eab2e2-b5cb-11e6-8c55-865f3c6dfecb.png)

**Comment by RyanCCollins** [comment]
Sadly, I ran out of free hours on Heroku.  The application should run locally and I should be able to restart the server in a couple of days.  Sorry for the inconvenience and thanks so much for reporting it!!
