### ISSUE TITLE
TypeError: node is null

### ISSUE THREAD

**Issue by rohitRev** [RyanCCollins/scalable-react-boilerplate#55]
HI Ryan 
I am getting the following error while installing the boiler plate

offline-plugin: runtime.install() was executed without OfflinePlugin being added to webpack.config.js. The installation of offline-plugin has not been performed. You can ignore this message if you are skipping the OfflinePlugin during development. Otherwise, you may have a configuration issue.

Error: Permission denied to access property Symbol.toPrimitive

TypeError: node is null
Please have a look at the files attached

![error1](https://cloud.githubusercontent.com/assets/24546125/21142092/87b6c55a-c166-11e6-84a7-8f2a4d4c8552.PNG)
![error2](https://cloud.githubusercontent.com/assets/24546125/21142093/87bc458e-c166-11e6-8473-32f92e4cf6cd.PNG)

**Comment by RyanCCollins** [comment]
Hey I am sorry you are having difficulties and I am also sorry for the delay in getting back with you.  I am not able to reproduce this.  If it's still an issue for you, please let me know and I can try to help.
