### ISSUE TITLE
Can the stable branch be used for production ?

### ISSUE THREAD

**Issue by narmadham** [RyanCCollins/scalable-react-boilerplate#59]
Hi,

I am trying to use the stable branch for my application. I am getting some exceptions. I don't require GraphQL but looking for SSR, Code splitting.  Please let me know whether stable branch can be used.

**Comment by RyanCCollins** [comment]
Hi @narmadham!

The stable branch was created a while back when we branched off into adding apollo / graphql.  I have not updated it in a while.  It was stable at the time.

I can create a branch that removes the graphql / apollo stuff, however, as the configuration for that is very small.

**Comment by narmadham** [comment]
Thanks @RyanCCollins ...That will be really helpful.

**Comment by RyanCCollins** [comment]
Sure, my pleasure!  I will ping you when it's ready.

**Comment by RyanCCollins** [comment]
Okay, I've removed apollo from the server and client.  There might be some configuration for apollo left behind, but nothing that will get in the way.  See [sans-apollo](https://github.com/RyanCCollins/scalable-react-boilerplate/tree/sans-apollo).  If you are working from a fork, you can feel free to pull stable into master, or whatever you need to do.  

All the best!

**Comment by RyanCCollins** [comment]
@narmadham I am going to close this, but please feel free to ping me if you have any other questions.

Cheers!

**Comment by narmadham** [comment]
Thanks @RyanCCollins  :)

**Comment by RyanCCollins** [comment]
My pleasure!
