### ISSUE TITLE
How do I define nested routes?

### ISSUE THREAD

**Issue by developer239** [RyanCCollins/scalable-react-boilerplate#61]
How do you define nested routes when you don't use jsx?

**Comment by RyanCCollins** [comment]
Hey @developer239!  You can see an example in the [react router docs](https://github.com/ReactTraining/react-router/blob/master/docs/guides/RouteConfiguration.md#configuration-with-plain-routes). You're looking for the child routes.

**Comment by RyanCCollins** [comment]
Please let me know if you have any further questions @developer239
