### ISSUE TITLE
How about normalise state ??

### ISSUE THREAD

**Issue by thonymg** [RyanCCollins/scalable-react-boilerplate#69]
In the redux documentation ...

> In a more complex app, you're going to want different entities to reference each other. We suggest that you keep your state as normalized as possible, without any nesting. Keep every entity in an object stored with an ID as a key, and use IDs to reference it from other entities, or lists. Think of the app's state as a database. This approach is described in normalizr's documentation in detail. For example, keeping todosById: { id -> todo } and todos: array<id> inside the state would be a better idea in a real app, but we're keeping the example simple.

QraphQl can do this job or we need to use [normalizr](https://github.com/paularmstrong/normalizr) ?

Thanks

**Comment by RyanCCollins** [comment]
Hey @thonymg, sure!  This sounds like a great opportunity for a pull request!  If you get around to it, feel free to submit it and I'd be happy to merge it in!

Thanks!

**Comment by RyanCCollins** [comment]
Hey @thonymg, I have closed this issue but feel free to reopen it at any time if you get back to it.
