### ISSUE TITLE
Deploy fails "Element from loaders list with objects should have a 'loader' specified"

### ISSUE THREAD

**Issue by Thefly75** [RyanCCollins/scalable-react-boilerplate#70]
First of all, thanks for your work, awesome boilerplate!

But I can't run the deploy script. Even with a fresh and new clone, the deploy script fails with:

> Element from loaders list with objects should have a 'loader' specified

Most likely the "ExtractTextPlugin" config part is causing this.

- Windows10
- Node v6.9.1

I tried different webpack and ExtractTextPlugin versions, without any luck.

**Comment by RyanCCollins** [comment]
Hey @Thefly75, this error popped up with a recent release of Extract text it looks like.  I've reverted it to the version that was compatible with the webpack version we are using here.

```
"extract-text-webpack-plugin": "v2.0.0-beta.4",
```

Please try that out and let me know how it goes.  You can pull from master to get these changes.

**Comment by Thefly75** [comment]
Thanks @RyanCCollins ! That really did the trick. All good now, thanks for the fast response!

**Comment by RyanCCollins** [comment]
My pleasure! Good to hear.  Feel free to reopen if you have any more difficulties!
